run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - typecheck     # Type checking
    - unused        # Find unused code
    - gosec         # Security issues
    - bodyclose     # HTTP body close
    - contextcheck  # Context checking
    - durationcheck # Duration checks
    - errorlint     # Error wrapping
    - nilerr        # nil error returns
    - sqlclosecheck # SQL close checks

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  gosec:
    excludes:
      - G104  # Audit errors not checked (we use errcheck)
      - G304  # File path provided as taint input (false positives)

issues:
  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    
    # Exclude template.go from some checks
    - path: internal/views/template\.go
      linters:
        - errcheck

  max-issues-per-linter: 50
  max-same-issues: 10